name: window_decoration_macos
description: macOS implementation of the window_decoration plugin
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.1'

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  window_decoration_platform_interface:
    path: ../window_decoration_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: window_decoration
    platforms:
      macos:
        dartPluginClass: WindowDecorationMacOS
        pluginClass: WindowDecorationMacOSPlugin
